# Generated by Django 6.1.1 on 2026-10-02 15:53

import tags.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, validators=[tags.models.reject_invisible_characters, tags.models.reject_commas]),
        ),
    ]
