"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from config.env import resolve_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Environment-specific settings come from the process environment and the
# repo-root .env (see .env.example); the process environment wins.
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/
_env = resolve_settings(os.environ, BASE_DIR.parent / ".env")

SECRET_KEY = _env.secret_key

DEBUG = _env.debug

ALLOWED_HOSTS = _env.allowed_hosts

# OpenAI Chat Completions, used by the ai app (ai.services).
OPENAI_API_KEY = _env.openai_api_key

OPENAI_MODEL = _env.openai_model


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Django's own form templates, for the TemplatesSetting renderer below.
    "django.forms",
    "django_tailwind_cli",
    "core",
    "accounts",
    "tags",
    "profiles",
    "goals",
    "learning_sessions",
    "resources",
    "dashboard",
    "ai",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# Forms render with the TEMPLATES engine, so the project's templates/forms/*
# (used by core.forms.StyledFormMixin) are found; "django.forms" in
# INSTALLED_APPS supplies Django's own form and widget templates.
FORM_RENDERER = "django.forms.renderers.TemplatesSetting"

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# DATABASE_URL (the container sets one on its data volume), else src/db.sqlite3.
DATABASES = {
    "default": _env.database
    or {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Authentication
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth

AUTH_USER_MODEL = "accounts.User"
# Where sign-up and log-in send the user (a URL name, resolved): the dashboard.
LOGIN_REDIRECT_URL = "dashboard:index"
# Where login-required pages send anonymous visitors (a URL name, resolved).
LOGIN_URL = "accounts:login"
# Where log-out sends the user.
LOGOUT_REDIRECT_URL = "/"


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
# django-tailwind-cli builds css/tailwind.css into the first entry; the built
# file is git-ignored, so run 'manage.py tailwind build' after checkout.
STATICFILES_DIRS = [BASE_DIR / "assets"]

# Pinned, so builds are reproducible and don't look up the latest release.
TAILWIND_CLI_VERSION = "4.3.3"
# The committed source stylesheet with the vendored daisyUI plugin. Relative
# to BASE_DIR, and outside STATICFILES_DIRS so collectstatic doesn't publish it.
TAILWIND_CLI_SRC_CSS = "tailwind/source.css"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}
