"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import warnings
from pathlib import Path

from config.env import resolve_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Environment-specific settings come from the process environment and the
# repo-root .env (see .env.example); the process environment wins.
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/
_env = resolve_settings(os.environ, BASE_DIR.parent / ".env")

SECRET_KEY = _env.secret_key

DEBUG = _env.debug

ALLOWED_HOSTS = _env.allowed_hosts

# Needed when the site is reached through another origin, e.g. an HTTPS proxy.
CSRF_TRUSTED_ORIGINS = _env.csrf_trusted_origins

# HTTPS: on unless DEBUG, each one overridable through the environment (for a
# plain-HTTP local run, set the first three to False).
SECURE_SSL_REDIRECT = _env.ssl_redirect

# The container's HEALTHCHECK requests the favicon over plain HTTP inside the
# container. Matched against the path without its leading slash.
SECURE_REDIRECT_EXEMPT = [r"^favicon\.ico$"]

SESSION_COOKIE_SECURE = _env.session_cookie_secure

CSRF_COOKIE_SECURE = _env.csrf_cookie_secure

SECURE_HSTS_SECONDS = _env.hsts_seconds

# HSTS covers this host only: includeSubDomains and preload commit the whole
# domain, beyond this app, so they stay off and check --deploy is told so.
SILENCED_SYSTEM_CHECKS = ["security.W005", "security.W021"]

# Only behind a TLS-terminating proxy that sets X-Forwarded-Proto.
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https") if _env.proxy_ssl_header else None
)

# OpenAI Chat Completions, used by the ai app (ai.services).
OPENAI_API_KEY = _env.openai_api_key

OPENAI_MODEL = _env.openai_model


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Django's own form templates, for the TemplatesSetting renderer below.
    "django.forms",
    "django_tailwind_cli",
    # Failed log-in lockout (settings under Authentication).
    "axes",
    "core",
    "accounts",
    "tags",
    "profiles",
    "goals",
    "learning_sessions",
    "resources",
    "dashboard",
    "ai",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Serves STATIC_ROOT when DEBUG is off (the container); right after Security.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Last, as django-axes requires: swaps in the lockout response.
    "axes.middleware.AxesMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# Forms render with the TEMPLATES engine, so the project's templates/forms/*
# (used by core.forms.StyledFormMixin) are found; "django.forms" in
# INSTALLED_APPS supplies Django's own form and widget templates.
FORM_RENDERER = "django.forms.renderers.TemplatesSetting"

WSGI_APPLICATION = "config.wsgi.application"

# Keeps the suite on plain HTTP whatever DEBUG is (see config/runner.py).
TEST_RUNNER = "config.runner.TestRunner"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# DATABASE_URL (the container sets one on its data volume), else src/db.sqlite3.
DATABASES = {
    "default": _env.database
    or {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Authentication
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth

AUTH_USER_MODEL = "accounts.User"
# Where sign-up and log-in send the user (a URL name, resolved): the dashboard.
LOGIN_REDIRECT_URL = "dashboard:index"
# Where login-required pages send anonymous visitors (a URL name, resolved).
LOGIN_URL = "accounts:login"
# Where log-out sends the user.
LOGOUT_REDIRECT_URL = "/"

# django-axes refuses a locked-out log-in first (the app's and the admin's,
# with the database handler, so every worker sees the same counts); Django's
# model backend then logs the user in. With two backends, login() needs an
# explicit backend (see accounts.views.SignUpView).
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]
# The 5th failure is refused with the lockout page, and so is every attempt
# after it, even with the right password.
AXES_FAILURE_LIMIT = 5
# Counted per username and IP address together, so an attacker elsewhere can't
# lock a user out, nor one username lock out everyone behind an IP. Without
# django-ipware the IP is REMOTE_ADDR: behind a reverse proxy every client
# shares the proxy's, and the lockout is in effect per username.
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
# django-tailwind-cli builds css/tailwind.css into the first entry; the built
# file is git-ignored, so run 'manage.py tailwind build' after checkout.
STATICFILES_DIRS = [BASE_DIR / "assets"]

# collectstatic gathers the files here (git-ignored; the Docker build runs it).
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise stores a gzipped copy next to each file and serves it to clients
# that accept it. No hashed (manifest) names, so {% static %} URLs stay as they
# are and pages render without running collectstatic first.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

# Local runs and the test suite never run collectstatic, so STATIC_ROOT doesn't
# exist there, and WhiteNoise would warn about it on every start. The container
# build collects into it (scripts/docker-smoke.sh checks the CSS is served).
# Matched by WhiteNoise's wording: a module filter would match the caller (the
# request handler), not WhiteNoise.
warnings.filterwarnings("ignore", message=r"No directory at: ", category=UserWarning)

# Pinned, so builds are reproducible and don't look up the latest release.
TAILWIND_CLI_VERSION = "4.3.3"
# The committed source stylesheet with the vendored daisyUI plugin. Relative
# to BASE_DIR, and outside STATICFILES_DIRS so collectstatic doesn't publish it.
TAILWIND_CLI_SRC_CSS = "tailwind/source.css"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# The console in development; SMTP otherwise (check --deploy rejects the
# console). The app sends no email yet, so no SMTP host is configured.
MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend"
        if DEBUG
        else "django.core.mail.backends.smtp.EmailBackend",
    },
}
