# Generated by Django 6.1.1 on 2026-10-02 21:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import learning_sessions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0002_alter_goal_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, validators=[learning_sessions.models.reject_future_dates])),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='goals.goal')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 1), ('duration_minutes__lte', 1440)), name='learning_sessions_learningsession_duration_valid')],
            },
        ),
    ]
