# Generated by Django 6.1.1 on 2026-10-03 08:33

import django.db.models.deletion
import resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0002_alter_goal_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', resources.models.HttpURLField(max_length=2048)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('repo', 'Repo'), ('doc', 'Doc')], default='article', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='goals.goal')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('url__istartswith', 'http://'), ('url__istartswith', 'https://'), _connector='OR'), name='resources_resource_url_http'), models.CheckConstraint(condition=models.Q(('type__in', ('article', 'video', 'repo', 'doc'))), name='resources_resource_type_valid'), models.UniqueConstraint(fields=('goal', 'url'), name='resources_resource_goal_url_unique', violation_error_message='This goal already has this resource.')],
            },
        ),
    ]
