# Generated by Django 6.1.1 on 2026-10-02 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in-progress', 'In progress'), ('done', 'Done')], default='planned', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('planned', 'in-progress', 'done'))), name='goals_goal_status_valid'),
        ),
    ]
