# Generated by Django 6.1.1 on 2026-10-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_goal_status_goal_goals_goal_status_valid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ('-created_at', '-id')},
        ),
    ]
