# Generated by Django 6.1.1 on 2026-10-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_goal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
