# Generated by Django 6.1.1 on 2026-10-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0003_goal_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="next_steps",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="goal",
            name="next_steps_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
